### ISSUE TITLE
Tooltips don't display parameter type when line finishes with a period.

### ISSUE THREAD

**Issue by thepenguin1** [php-integrator/atom-tooltips#24]
Consider the following function / doc block:

```
/**
 * Create a custom error and add it to the error
 * message bag so it will be flashed to the session.
 * User is then redirected back, or to optional url.
 *
 * @param string $error.
 * @param string $url.
 * @param bool $force_json.
 * @return mixed.
 *
 **/
function abortWithError($error, $url = "", $force_json = false)
{
 ...
}
```

The resulting tooltip displays the parameters, but without their data type:

![screen shot 2017-01-19 at 11 09 20 am](https://cloud.githubusercontent.com/assets/19876593/22104572/d16b632a-de37-11e6-9392-84b22ddbaecc.png)

This appears to be caused by the period at the end of the parameter name.

**Comment by Gert-dev** [comment]
Thanks for reporting this, I've created a new ticket in the core that references this one since the actual parsing happens in the core (you couldn't know that before posting, so no problem that you posted it here!) and GitHub unfortunately doesn't allow relocating issues to related repositories.

**Comment by thepenguin1** [comment]
Thanks!
